name: Apresentação do workflow - Manual

on: [workflow_dispatch]

jobs:
  build_artifact:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven        

      - name: Construir com Maven
        run: mvn clean package

      - name: Logar no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN_REGISTRY }}          

      - name: Construir Imagem e Realizar Push para repositorio de imagens
        run: |
          docker build -t ghcr.io/${{ github.repository }}/minha-imagem:latest .
          docker push ghcr.io/${{ github.repository }}/minha-imagem:latest

  

