name: Apresentação do workflow - Manual

on: [workflow_dispatch]

jobs:
  build_artifact:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven        

      - name: Construir com Maven
        run: mvn clean package

      # Step 3: Login no GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN_REGISTRY }}  # O GITHUB_TOKEN já é configurado automaticamente no GitHub Actions


      - name: gerar hash baseado no timestamp
        run: |
          timestamp=$(date +%s)  # Pega o timestamp atual em segundos
          hash=$(echo -n "$timestamp" | shasum -a 256 | awk '{ print $1 }')
          echo "hash=$hash" >> $GITHUB_ENV
          echo "Generated hash from timestamp: $hash"

      # Step 4: Construir a imagem Docker
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/meu-app:${{ env.hash  }} .
          
      # Step 5: Fazer o push da imagem para o GitHub Container Registry (GHCR)
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}/meu-app:${{ env.hash  }}
          

  

