name: Apresentação do workflow - Manual

on: [workflow_dispatch]

jobs:
  build_artifact:
    runs-on: ubuntu-20.04  # maquina utilizada para rodar o worflow

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2 # realiza o checkout do projeto

      - name: Configurar JDK 21
        uses: actions/setup-java@v4 # configura versão do Java
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven        

      - name: Construir com Maven
        run: mvn clean package # realiza o build do projeto

      - name: Construir Imagem e Realizar Push para repositorio de imagens
        run: |
          docker build -t ghcr.io/${{ github.repository }}/minha-imagem:latest .
          docker push ghcr.io/${{ github.repository }}/minha-imagem:latest

      - name: Logar no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construir e fazer push da imagem Docker
        run: |
          docker build -t ghcr.io/${{ github.repository }}/minha-imagem .
          docker push ghcr.io/${{ github.repository }}/minha-imagem       

